name: Get_started
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Echo Hello World
      run: echo "Hello World!"
    - name: List Files
      run: |
        pwd
        ls -la
    - name: Read file
      run: cat .github/workflows/Jira_report.yml
