name: Get_started
on: push
jobs:
  first_job:
  runs_on: ubuntu-latest
  steps:
    - name: "Echo Hello World"
      run: echo "Hello World!"
    - name: "List Files"
      run: ls 
    - name: "Read file"
      run: cat .github/workflows/Jira_report.yml