name: Get_started
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Echo Hello World
      run: echo "Hello World!"
    - name: List Files
      run: |
        pwd
        ls -la
    - name: Read file
      run: cat .github/workflows/Jira_report.yml
    - name: Install tree
      run: sudo apt install tree -y 
    - name: Graphical listing of files
      run: tree /home/runner/work/GitHub-Actions/GitHub-Actions
    - name: Start httpd
      run: sudo systemctl start apache2
    - name: Httpd status check
      run: systemctl status apache2
    - name: Run shell script
      run: |
        sudo chmod +x user.sh
        sudo ./user.sh
